source "https://rubygems.org"
gem "rails", "4.2.3"
gem "mysql2"
gem "sass-rails", "~> 5.0"
gem "uglifier", ">= 1.3.0"
gem "coffee-rails", "~> 4.1.0"
gem "jquery-rails"
gem "turbolinks"
gem "jbuilder", "~> 2.0"
gem "sdoc", "~> 0.4.0", group: :doc
gem "bootstrap-sass"
gem "devise"
gem "font-awesome-rails"
gem "bootstrap-datepicker-rails"
gem "kaminari"
gem "bootstrap-kaminari-views"
gem "config"
gem "ransack"
gem "highcharts-rails", "~> 3.0.0"
group :development, :test do
  gem "byebug"
  gem "web-console", "~> 2.0"
  gem "spring"
end

