pagination:
  per_page: 10
intervals:
  daily: "daily"
  monthly: "monthly"
  yearly: "yearly"
payment_methods:
  all: "all"
types:
  income: "income"
  expense: "expense"
payment_class:
  user_income: "UserIncome"
  user_expense: "UserExpense"
